[2024-12-01T19:04:50.572+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-01T19:04:50.627+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: consume_kafka_to_hive.consume_kafka_messages manual__2024-12-01T19:04:43.885632+00:00 [queued]>
[2024-12-01T19:04:50.661+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: consume_kafka_to_hive.consume_kafka_messages manual__2024-12-01T19:04:43.885632+00:00 [queued]>
[2024-12-01T19:04:50.663+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-12-01T19:04:50.785+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): consume_kafka_messages> on 2024-12-01 19:04:43.885632+00:00
[2024-12-01T19:04:50.794+0000] {standard_task_runner.py:72} INFO - Started process 331 to run task
[2024-12-01T19:04:50.798+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'consume_kafka_to_hive', 'consume_kafka_messages', 'manual__2024-12-01T19:04:43.885632+00:00', '--job-id', '61', '--raw', '--subdir', 'DAGS_FOLDER/consume_kafka_to_hive.py', '--cfg-path', '/tmp/tmpcntgq_i0']
[2024-12-01T19:04:50.803+0000] {standard_task_runner.py:105} INFO - Job 61: Subtask consume_kafka_messages
[2024-12-01T19:04:51.031+0000] {task_command.py:467} INFO - Running <TaskInstance: consume_kafka_to_hive.consume_kafka_messages manual__2024-12-01T19:04:43.885632+00:00 [running]> on host 45770b1a429e
[2024-12-01T19:04:51.333+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='consume_kafka_to_hive' AIRFLOW_CTX_TASK_ID='consume_kafka_messages' AIRFLOW_CTX_EXECUTION_DATE='2024-12-01T19:04:43.885632+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-01T19:04:43.885632+00:00'
[2024-12-01T19:04:51.336+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-01T19:04:51.609+0000] {hive.py:475} INFO - USE `default`
[2024-12-01T19:04:51.846+0000] {hive.py:475} INFO - 
    CREATE TABLE IF NOT EXISTS sales (
        id STRING,
        invoice_id STRING,
        branch STRING,
        city STRING,
        customer_type STRING,
        gender STRING,
        product_line STRING,
        unit_price FLOAT,
        quantity INT,
        tax_5_percent FLOAT,
        total FLOAT,
        `date` STRING,
        time STRING,
        payment STRING,
        cogs FLOAT,
        gross_margin_percentage FLOAT,
        gross_income FLOAT,
        rating FLOAT
    ) STORED AS ORC
    
[2024-12-01T20:21:07.067+0000] {local_task_job_runner.py:346} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2024-12-01T20:21:07.077+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-12-01T20:21:07.083+0000] {process_utils.py:132} INFO - Sending 15 to group 331. PIDs of all processes in the group: [331]
[2024-12-01T20:21:07.084+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 331
[2024-12-01T20:21:07.544+0000] {taskinstance.py:3093} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-12-01T20:21:11.799+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-01T20:21:11.852+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=331, status='terminated', exitcode=0, started='19:04:49') (331) terminated with exit code 0
