[2024-12-02T18:44:43.624+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-02T18:44:43.663+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kafka_hive_pipeline.consume_from_kafka manual__2024-12-02T18:43:33.512281+00:00 [queued]>
[2024-12-02T18:44:43.692+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kafka_hive_pipeline.consume_from_kafka manual__2024-12-02T18:43:33.512281+00:00 [queued]>
[2024-12-02T18:44:43.693+0000] {taskinstance.py:2866} INFO - Starting attempt 2 of 1
[2024-12-02T18:44:43.758+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): consume_from_kafka> on 2024-12-02 18:43:33.512281+00:00
[2024-12-02T18:44:43.782+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=568) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-12-02T18:44:43.778+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'kafka_hive_pipeline', 'consume_from_kafka', 'manual__2024-12-02T18:43:33.512281+00:00', '--job-id', '154', '--raw', '--subdir', 'DAGS_FOLDER/gestion_airflow.py', '--cfg-path', '/tmp/tmpnkqcy3o2']
[2024-12-02T18:44:43.785+0000] {standard_task_runner.py:72} INFO - Started process 582 to run task
[2024-12-02T18:44:43.787+0000] {standard_task_runner.py:105} INFO - Job 154: Subtask consume_from_kafka
[2024-12-02T18:44:43.979+0000] {task_command.py:467} INFO - Running <TaskInstance: kafka_hive_pipeline.consume_from_kafka manual__2024-12-02T18:43:33.512281+00:00 [running]> on host 45770b1a429e
[2024-12-02T18:44:44.194+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='kafka_hive_pipeline' AIRFLOW_CTX_TASK_ID='consume_from_kafka' AIRFLOW_CTX_EXECUTION_DATE='2024-12-02T18:43:33.512281+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-02T18:43:33.512281+00:00'
[2024-12-02T18:44:44.196+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-02T18:44:44.526+0000] {hive.py:475} INFO - USE `default`
[2024-12-02T18:44:44.695+0000] {hive.py:475} INFO - 
    CREATE TABLE IF NOT EXISTS sales (
        id STRING,
        invoice_id STRING,
        branch STRING,
        city STRING,
        customer_type STRING,
        gender STRING,
        product_line STRING,
        unit_price FLOAT,
        quantity INT,
        tax_5_percent FLOAT,
        total FLOAT,
        `date` STRING,
        time STRING,
        payment STRING,
        cogs FLOAT,
        gross_margin_percentage FLOAT,
        gross_income FLOAT,
        rating FLOAT
    ) STORED AS ORC
    
[2024-12-02T18:44:44.734+0000] {kafka_to_hive_with_redis.py:70} INFO - Subscribed to topic 'topic-batch'
[2024-12-02T18:44:54.057+0000] {local_task_job_runner.py:346} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2024-12-02T18:44:54.058+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-12-02T18:44:54.060+0000] {process_utils.py:132} INFO - Sending 15 to group 582. PIDs of all processes in the group: [582]
[2024-12-02T18:44:54.061+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 582
[2024-12-02T18:44:54.739+0000] {taskinstance.py:3093} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-12-02T18:44:54.837+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-02T18:44:54.879+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=582, status='terminated', exitcode=0, started='18:44:43') (582) terminated with exit code 0
