[2024-11-29T22:43:48.946+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-29T22:43:48.984+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag1.process_task_tag2 manual__2024-11-29T22:43:42.482647+00:00 [queued]>
[2024-11-29T22:43:49.014+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag1.process_task_tag2 manual__2024-11-29T22:43:42.482647+00:00 [queued]>
[2024-11-29T22:43:49.016+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2024-11-29T22:43:49.111+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): process_task_tag2> on 2024-11-29 22:43:42.482647+00:00
[2024-11-29T22:43:49.148+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'dag1', 'process_task_tag2', 'manual__2024-11-29T22:43:42.482647+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/dag_data.py', '--cfg-path', '/tmp/tmpjmbdhg8n']
[2024-11-29T22:43:49.157+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=409) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-29T22:43:49.164+0000] {standard_task_runner.py:105} INFO - Job 12: Subtask process_task_tag2
[2024-11-29T22:43:49.164+0000] {standard_task_runner.py:72} INFO - Started process 423 to run task
[2024-11-29T22:43:49.395+0000] {task_command.py:467} INFO - Running <TaskInstance: dag1.process_task_tag2 manual__2024-11-29T22:43:42.482647+00:00 [running]> on host bffe5982c6e9
[2024-11-29T22:43:49.717+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airscholar' AIRFLOW_CTX_DAG_ID='dag1' AIRFLOW_CTX_TASK_ID='process_task_tag2' AIRFLOW_CTX_EXECUTION_DATE='2024-11-29T22:43:42.482647+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-29T22:43:42.482647+00:00'
[2024-11-29T22:43:49.719+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-29T22:43:49.769+0000] {dag_data.py:61} ERROR - Une erreur est survenue lors du traitement de sales.csv : KafkaError{code=_INVALID_ARG,val=-186,str="No such configuration property: "bootstrap_servers""}
[2024-11-29T22:43:49.771+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-11-29T22:43:49.796+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-29T22:43:49.797+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dag1, task_id=process_task_tag2, run_id=manual__2024-11-29T22:43:42.482647+00:00, execution_date=20241129T224342, start_date=20241129T224348, end_date=20241129T224349
[2024-11-29T22:43:49.912+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-11-29T22:43:49.956+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-29T22:43:49.960+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
