[2024-12-04T08:47:37.829+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-04T08:47:37.867+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_tohive.process_task_tohive scheduled__2024-12-03T00:00:00+00:00 [queued]>
[2024-12-04T08:47:37.890+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_tohive.process_task_tohive scheduled__2024-12-03T00:00:00+00:00 [queued]>
[2024-12-04T08:47:37.891+0000] {taskinstance.py:2866} INFO - Starting attempt 3 of 1
[2024-12-04T08:47:37.973+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): process_task_tohive> on 2024-12-03 00:00:00+00:00
[2024-12-04T08:47:37.983+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=153) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-12-04T08:47:37.985+0000] {standard_task_runner.py:72} INFO - Started process 167 to run task
[2024-12-04T08:47:37.984+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'dag_tohive', 'process_task_tohive', 'scheduled__2024-12-03T00:00:00+00:00', '--job-id', '191', '--raw', '--subdir', 'DAGS_FOLDER/dag_9lines_data.py', '--cfg-path', '/tmp/tmpv5k8ih4g']
[2024-12-04T08:47:37.986+0000] {standard_task_runner.py:105} INFO - Job 191: Subtask process_task_tohive
[2024-12-04T08:47:38.139+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_tohive.process_task_tohive scheduled__2024-12-03T00:00:00+00:00 [running]> on host 45770b1a429e
[2024-12-04T08:47:38.336+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='dag_tohive' AIRFLOW_CTX_TASK_ID='process_task_tohive' AIRFLOW_CTX_EXECUTION_DATE='2024-12-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-03T00:00:00+00:00'
[2024-12-04T08:47:38.338+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-04T08:47:38.395+0000] {dag_9lines_data.py:22} INFO - Message delivered to tohive [0]
[2024-12-04T08:47:38.396+0000] {dag_9lines_data.py:22} INFO - Message delivered to tohive [0]
[2024-12-04T08:47:38.397+0000] {dag_9lines_data.py:22} INFO - Message delivered to tohive [0]
[2024-12-04T08:47:38.398+0000] {dag_9lines_data.py:22} INFO - Message delivered to tohive [0]
[2024-12-04T08:47:38.398+0000] {dag_9lines_data.py:22} INFO - Message delivered to tohive [0]
[2024-12-04T08:47:38.399+0000] {dag_9lines_data.py:22} INFO - Message delivered to tohive [0]
[2024-12-04T08:47:38.400+0000] {dag_9lines_data.py:22} INFO - Message delivered to tohive [0]
[2024-12-04T08:47:38.400+0000] {dag_9lines_data.py:22} INFO - Message delivered to tohive [0]
[2024-12-04T08:47:38.401+0000] {dag_9lines_data.py:22} INFO - Message delivered to tohive [0]
[2024-12-04T08:47:38.401+0000] {dag_9lines_data.py:74} INFO - Toutes les données de test.csv ont été publiées avec succès.
[2024-12-04T08:47:38.403+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-12-04T08:47:38.421+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-04T08:47:38.422+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dag_tohive, task_id=process_task_tohive, run_id=scheduled__2024-12-03T00:00:00+00:00, execution_date=20241203T000000, start_date=20241204T084737, end_date=20241204T084738
[2024-12-04T08:47:38.510+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-04T08:47:38.541+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-04T08:47:38.544+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-12-04T08:48:04.873+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-04T08:48:04.897+0000] {taskinstance.py:2603} INFO - Dependencies not met for <TaskInstance: dag_tohive.process_task_tohive scheduled__2024-12-03T00:00:00+00:00 [success]>, dependency 'Task Instance State' FAILED: Task is in the 'success' state.
[2024-12-04T08:48:04.911+0000] {local_task_job_runner.py:166} INFO - Task is not able to be run
