[2024-12-01T20:41:05.642+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-01T20:41:05.680+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: consume_kafka_to_hive.consume_kafka_messages manual__2024-12-01T20:40:58.267152+00:00 [queued]>
[2024-12-01T20:41:05.707+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: consume_kafka_to_hive.consume_kafka_messages manual__2024-12-01T20:40:58.267152+00:00 [queued]>
[2024-12-01T20:41:05.709+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-12-01T20:41:05.797+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): consume_kafka_messages> on 2024-12-01 20:40:58.267152+00:00
[2024-12-01T20:41:05.811+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'consume_kafka_to_hive', 'consume_kafka_messages', 'manual__2024-12-01T20:40:58.267152+00:00', '--job-id', '72', '--raw', '--subdir', 'DAGS_FOLDER/consume_kafka_to_hive.py', '--cfg-path', '/tmp/tmp5mrhsds7']
[2024-12-01T20:41:05.809+0000] {standard_task_runner.py:72} INFO - Started process 207 to run task
[2024-12-01T20:41:05.822+0000] {standard_task_runner.py:105} INFO - Job 72: Subtask consume_kafka_messages
[2024-12-01T20:41:06.156+0000] {task_command.py:467} INFO - Running <TaskInstance: consume_kafka_to_hive.consume_kafka_messages manual__2024-12-01T20:40:58.267152+00:00 [running]> on host 45770b1a429e
[2024-12-01T20:41:06.567+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='consume_kafka_to_hive' AIRFLOW_CTX_TASK_ID='consume_kafka_messages' AIRFLOW_CTX_EXECUTION_DATE='2024-12-01T20:40:58.267152+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-01T20:40:58.267152+00:00'
[2024-12-01T20:41:06.572+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-01T20:41:07.103+0000] {hive.py:475} INFO - USE `default`
[2024-12-01T20:41:08.950+0000] {hive.py:475} INFO - 
    CREATE TABLE IF NOT EXISTS sales (
        id STRING,
        invoice_id STRING,
        branch STRING,
        city STRING,
        customer_type STRING,
        gender STRING,
        product_line STRING,
        unit_price FLOAT,
        quantity INT,
        tax_5_percent FLOAT,
        total FLOAT,
        `date` STRING,
        time STRING,
        payment STRING,
        cogs FLOAT,
        gross_margin_percentage FLOAT,
        gross_income FLOAT,
        rating FLOAT
    ) STORED AS ORC
    
[2024-12-01T20:45:45.964+0000] {local_task_job_runner.py:346} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2024-12-01T20:45:45.964+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-12-01T20:45:45.966+0000] {process_utils.py:132} INFO - Sending 15 to group 207. PIDs of all processes in the group: [207]
[2024-12-01T20:45:45.966+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 207
[2024-12-01T20:45:46.370+0000] {taskinstance.py:3093} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-12-01T20:45:50.206+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-01T20:45:50.249+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=207, status='terminated', exitcode=0, started='20:41:05') (207) terminated with exit code 0
